package at.asitplus.wallet.backend

import at.asitplus.wallet.lib.decodeBase64ToArray
import at.asitplus.wallet.lib.encodeBase64
import io.kotest.matchers.nulls.shouldBeNull
import io.kotest.matchers.nulls.shouldNotBeNull
import io.kotest.matchers.shouldBe
import org.junit.jupiter.api.Test
import java.time.Instant
import java.util.Date
import java.util.UUID
import kotlin.test.expect

class DefaultAttestationServiceTest {

    private val service = DefaultAttestationService(InMemoryCertificateService())

    @Test
    fun `android attestation`() {
        val attestationChain = listOf(
            """MIICdzCCAh2gAwIBAgIBATAKBggqhkjOPQQDAjApMRkwFwYDVQQFExBhMzM2MjM0MjQ5ODYwZTYxMQwwCgYDVQQMDANURUUwIBcNNzAw
                |MTAxMDAwMDAwWhgPMjEwNjAyMDcwNjI4MTVaMB8xHTAbBgNVBAMMFEFuZHJvaWQgS2V5c3RvcmUgS2V5MFkwEwYHKoZIzj0CAQYIKo
                |ZIzj0DAQcDQgAEkpxN4fMkWg5cRvioj+DzaYr0Chxu5ewvNrFM77rqrhJ4VNam9R2bLlYu2CoA/ByifzdZ1qBJgw57KBBEyTSf7aOC
                |ATwwggE4MA4GA1UdDwEB/wQEAwIHgDCCASQGCisGAQQB1nkCAREEggEUMIIBEAIBAgoBAQIBAwoBAQQg7z7M0NWSbDuyjK8wpJ9CD+
                |6dew7/+jg8JK1g6uKqbOgEADBhv4U9CAIGAYAYr8DIv4VFUQRPME0xJzAlBCBhdC5hc2l0cGx1cy5kaWdpdGFsaWQud2FsbGV0LmFi
                |bgIBATEiBCDlQaigNLb1SF5cvLPXauVNsHfq//f3qaeunJykbHSqUjB7oQgxBgIBAgIBA6IDAgEDowQCAgEApQsxCQIBBAIBAgIBAK
                |oDAgEBv4N4AwIBAr+FPgMCAQC/hT8CBQC/hUAqMCgEIBGUZZtA6ikSReVKPE7Eqltwd70kTWXH3YwKLbudsfs1AQH/CgEAv4VBBQID
                |AYagv4VCBQIDAxUbMAoGCCqGSM49BAMCA0gAMEUCIQCLLvYSC5RK8tzeBl2LGMjheWpbmS+u9z6wMIRXoHVhPwIgMh2FA67Tf7yFBr
                |zbZakp9RA1Q7KM/PgivpFWhmsIw/0=""".trimMargin(),
            """MIICJTCCAaugAwIBAgIKE1OIURhkIAaGZjAKBggqhkjOPQQDAjApMRkwFwYDVQQFExBmYjFjMTA3OTk4NTViZTFkMQwwCgYDVQQMDANU
                |RUUwHhcNMTgwNDE4MTk1MDI2WhcNMjgwNDE1MTk1MDI2WjApMRkwFwYDVQQFExBhMzM2MjM0MjQ5ODYwZTYxMQwwCgYDVQQMDANURU
                |UwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARcpzo1igvQIcWYnqviUJv25fhx50/VuaIZ0l95zftGkdOY2fXyezvik1jeQnFLpPGb
                |LFVi5MI/Nb+vs77TppxIo4G6MIG3MB0GA1UdDgQWBBSGQ6mY0u2S7XV9psRTDSnqmuUXMTAfBgNVHSMEGDAWgBQhb4iEobma5qWw4C
                |rzN3lhgFOswjAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwICBDBUBgNVHR8ETTBLMEmgR6BFhkNodHRwczovL2FuZHJvaWQu
                |Z29vZ2xlYXBpcy5jb20vYXR0ZXN0YXRpb24vY3JsLzEzNTM4ODUxMTg2NDIwMDY4NjY2MAoGCCqGSM49BAMCA2gAMGUCMQDBkU/REK
                |mgE7f09NkmHIeZjgcH74Wt5pVJWKKpihywOzhtefW9+3lkrvfl3eLwS4cCMFb6LoiAXVMuN8GBaAlVb6oTWj01jDWwzG1aCQwd82FO
                |toVLHWwqlFpyTjJJ1JUE1A==""".trimMargin(),
            """MIID0TCCAbmgAwIBAgIKA4gmZ2BliZaFjTANBgkqhkiG9w0BAQsFADAbMRkwFwYDVQQFExBmOTIwMDllODUzYjZiMDQ1MB4XDTE4MDQx
                |ODE5MzEyNFoXDTI4MDQxNTE5MzEyNFowKTEZMBcGA1UEBRMQZmIxYzEwNzk5ODU1YmUxZDEMMAoGA1UEDAwDVEVFMHYwEAYHKoZIzj
                |0CAQYFK4EEACIDYgAE+0hg15QPO5GKiQvsPrO5YOxx4t7hUJQMhYKlY8DFA5R4AQ5fekBQj+KTQUHqrAuYXjN4TVhMP8IVLEGkqIO+
                |1enKL++jy7HhnOroiVITRa09zOZP0q09j8GWU6mau3oAo4G2MIGzMB0GA1UdDgQWBBQhb4iEobma5qWw4CrzN3lhgFOswjAfBgNVHS
                |MEGDAWgBQ2YeEAfIgFCVGLRGxH/xpMyepPEjAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwICBDBQBgNVHR8ESTBHMEWgQ6BB
                |hj9odHRwczovL2FuZHJvaWQuZ29vZ2xlYXBpcy5jb20vYXR0ZXN0YXRpb24vY3JsL0U4RkExOTYzMTREMkZBMTgwDQYJKoZIhvcNAQ
                |ELBQADggIBAHFY/PrwyOng+DhG3jTMYZJLAADOiX1IkFMQCwyAbmgrsoI11GUGflMHhSk/im6lSCBoFZbR5k6JiA9PdmvU+rfXlFLN
                |OdXSM30W12PWfbzwJmKjL5duxaYW+J3SRfJhWTlhnHS7BE5w7zV+g6VRkrE9GhQhMoogbeHLJ5nXndyKtQElQgqCTV82Qx4Rg7Y9En
                |Zy2ojINvmGnziE1v95uHlLBLHT7mkBoUr1AvKwomAbir15x3AmfZQ+j/K7iVfgBAYUDd74csigXmKDjReAnYrh1s9tlw1780JeM/Ge
                |Q+u3XlMkAacB0jLXdWyJpyO14S58KeYemcquMfuwe3eXQuoT8xaEgVyHLyeLkUTd3BU8marG3Zfel5QmEz/7Ktgfft0eoenFhDqWbK
                |Utn418PfI8m1xqoCySHXebeAQnf8plAVu+QXCRR0r9rE/1GgwxV0Ba96nL5J8a5K0dDcwAbJwvffiuGlUvpOR0Qg/MB46EpekZtL/a
                |8+sVEbsJljWLiFB/D3QKOT4hZ7XBlpyQmxEq9lT/2ZGwXogr+P5f/W01TtLuu8zLoCoZzGl/3r360eASau2d+17wB9tvNb8JDnkr8v
                |2WkPVDAbdLZw1FmOzhLFOPqlQ6HYAYJDkU/zvW7ovvmuIDrubC1w+neeAtwP9T2g2e8XbReH5lLV5reV67""".trimMargin(),
            """MIIFYDCCA0igAwIBAgIJAOj6GWMU0voYMA0GCSqGSIb3DQEBCwUAMBsxGTAXBgNVBAUTEGY5MjAwOWU4NTNiNmIwNDUwHhcNMTYwNTI2
                |MTYyODUyWhcNMjYwNTI0MTYyODUyWjAbMRkwFwYDVQQFExBmOTIwMDllODUzYjZiMDQ1MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMI
                |ICCgKCAgEAr7bHgiuxpwHsK7Qui8xUFmOr75gvMsd/dTEDDJdSSxtf6An7xyqpRR90PL2abxM1dEqlXnf2tqw1Ne4Xwl5jlRfdnJLm
                |N0pTy/4lj4/7tv0Sk3iiKkypnEUtR6WfMgH0QZfKHM1+di+y9TFRtv6y//0rb+T+W8a9nsNL/ggjnar86461qO0rOs2cXjp3kOG1FE
                |J5MVmFmBGtnrKpa73XpXyTqRxB/M0n1n/W9nGqC4FSYa04T6N5RIZGBN2z2MT5IKGbFlbC8UrW0DxW7AYImQQcHtGl/m00QLVWutHQ
                |oVJYnFPlXTcHYvASLu+RhhsbDmxMgJJ0mcDpvsC4PjvB+TxywElgS70vE0XmLD+OJtvsBslHZvPBKCOdT0MS+tgSOIfga+z1Z1g7+D
                |Vagf7quvmag8jfPioyKvxnK/EgsTUVi2ghzq8wm27ud/mIM7AY2qEORR8Go3TVB4HzWQgpZrt3i5MIlCaY504LzSRiigHCzAPlHws+
                |W0rB5N+er5/2pJKnfBSDiCiFAVtCLOZ7gLiMm0jhO2B6tUXHI/+MRPjy02i59lINMRRev56GKtcd9qO/0kUJWdZTdA2XoS82ixPvZt
                |XQpUpuL12ab+9EaDK8Z4RHJYYfCT3Q5vNAXaiWQ+8PTWm2QgBR/bkwSWc+NpUFgNPN9PvQi8WEg5UmAGMCAwEAAaOBpjCBozAdBgNV
                |HQ4EFgQUNmHhAHyIBQlRi0RsR/8aTMnqTxIwHwYDVR0jBBgwFoAUNmHhAHyIBQlRi0RsR/8aTMnqTxIwDwYDVR0TAQH/BAUwAwEB/z
                |AOBgNVHQ8BAf8EBAMCAYYwQAYDVR0fBDkwNzA1oDOgMYYvaHR0cHM6Ly9hbmRyb2lkLmdvb2dsZWFwaXMuY29tL2F0dGVzdGF0aW9u
                |L2NybC8wDQYJKoZIhvcNAQELBQADggIBACDIw41L3KlXG0aMiS//cqrG+EShHUGo8HNsw30W1kJtjn6UBwRM6jnmiwfBPb8VA91chb
                |2vssAtX2zbTvqBJ9+LBPGCdw/E53Rbf86qhxKaiAHOjpvAy5Y3m00mqC0w/Zwvju1twb4vhLaJ5NkUJYsUS7rmJKHHBnETLi8GFqiE
                |sqTWpG/6ibYCv7rYDBJDcR9W62BW9jfIoBQcxUCUJouMPH25lLNcDc1ssqvC2v7iUgI9LeoM1sNovqPmQUiG9rHli1vXxzCyaMTjwf
                |tkJLkf6724DFhuKug2jITV0QkXvaJWF4nUaHOTNA4uJU9WDvZLI1j83A+/xnAJUucIv/zGJ1AMH2boHqF8CY16LpsYgBt6tKxxWH00
                |XcyDCdW2KlBCeqbQPcsFmWyWugxdcekhYsAWyoSf818NUsZdBWBaR/OukXrNLfkQ79IyZohZbvabO/X+MVT3rriAoKc8oE2Uws6DF+
                |60PV7/WIPjNvXySdqspImSN78mflxDqwLqRBYkA3I75qppLGG9rp7UCdRjxMl8ZDBld+7yvHVgt1cVzJx9xnyGCC23UaicMDSXYrB4
                |I4WHXPGjxhZuCuPBLTdOLU8YRvMYdEvYebWHMpvwGCF6bAx3JBpIeOQ1wDB5y0USicV3YgYGmi+NZfhA4URSh77Yd6uuJOJENRaNVT
                |zk""".trimMargin()
        ).map { it.decodeBase64ToArray()!! }

        val expectedPublicKey =
            "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEkpxN4fMkWg5cRvioj+DzaYr0Chxu5ewvNrFM77rqrhJ4VNam9R2bLlYu2CoA/ByifzdZ1qBJgw57KBBEyTSf7Q==".decodeBase64ToArray()!!
        service.extractVerifiedPublicKey(attestationChain) shouldBe expectedPublicKey

        service.extractVerifiedPublicKey(listOf(attestationChain[0])).shouldBeNull()
        service.extractVerifiedPublicKey(attestationChain.subList(0, 1)).shouldBeNull()
        service.extractVerifiedPublicKey(attestationChain.subList(0, 2)).shouldBeNull()
    }

    @Test
    fun `iOS attestation`() {
        val attestationStatement = """
            o2NmbXRvYXBwbGUtYXBwYXR0ZXN0Z2F0dFN0bXSiY3g1Y4JZAuswggLnMIICbaADAgECAgYBd7RVV1MwCgYIKoZIzj0EAwIwTzEjMCEGA1U
            EAwwaQXBwbGUgQXBwIEF0dGVzdGF0aW9uIENBIDExEzARBgNVBAoMCkFwcGxlIEluYy4xEzARBgNVBAgMCkNhbGlmb3JuaWEwHhcNMjEwMj
            E3MDg1MDI3WhcNMjEwMjIwMDg1MDI3WjCBkTFJMEcGA1UEAwxANDYwMjNlYzg3N2YwMWY2MGQyNzFlMDQ3MzI0MTM2YzE4ZTQwZjg0YjdlM
            zkwZjA5NDY2MDI0NWZlZjBiYzkzZTEaMBgGA1UECwwRQUFBIENlcnRpZmljYXRpb24xEzARBgNVBAoMCkFwcGxlIEluYy4xEzARBgNVBAgM
            CkNhbGlmb3JuaWEwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQJOxeGQyD0cdx9X69m592Kr3eBoGJu27ay7bmoyCwjWoCnHRru7sKbFv7
            idwZr8mIV0OATqSm0zK8aL87vBq5so4HxMIHuMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgTwMH4GCSqGSIb3Y2QIBQRxMG+kAwIBCr
            +JMAMCAQG/iTEDAgEAv4kyAwIBAb+JMwMCAQG/iTQmBCQ5Q1lISk5HNjQ0LmF0LmFzaXRwbHVzLm9lZ3YtZGVtby1hcHClBgQEc2tzIL+JN
            gMCAQW/iTcDAgEAv4k5AwIBAL+JOgMCAQAwGQYJKoZIhvdjZAgHBAwwCr+KeAYEBDE0LjQwMwYJKoZIhvdjZAgCBCYwJKEiBCAX4oF9z9dI
            E+ZUI+k9HiBWvKAQn/ZjfG3b4eCapklpbDAKBggqhkjOPQQDAgNoADBlAjEAqqtj8V2EoNNzYOnWYWojk+U8+rrPy5nrKEpQEM+NHwii8Pa
            mVHMSz9n6fOqv4EHeAjBMOcm64dLRzBBqqgFax1Pg6EpaN7VWqcn7YfHqZGeIpkkOUipFyhhTq11wR6BSUAhZAkcwggJDMIIByKADAgECAh
            AJusXhvEAa2dRTlbw4GghUMAoGCCqGSM49BAMDMFIxJjAkBgNVBAMMHUFwcGxlIEFwcCBBdHRlc3RhdGlvbiBSb290IENBMRMwEQYDVQQKD
            ApBcHBsZSBJbmMuMRMwEQYDVQQIDApDYWxpZm9ybmlhMB4XDTIwMDMxODE4Mzk1NVoXDTMwMDMxMzAwMDAwMFowTzEjMCEGA1UEAwwaQXBw
            bGUgQXBwIEF0dGVzdGF0aW9uIENBIDExEzARBgNVBAoMCkFwcGxlIEluYy4xEzARBgNVBAgMCkNhbGlmb3JuaWEwdjAQBgcqhkjOPQIBBgU
            rgQQAIgNiAASuWzegd015sjWPQOfR8iYm8cJf7xeALeqzgmpZh0/40q0VJXiaomYEGRJItjy5ZwaemNNjvV43D7+gjjKegHOphed0bqNZov
            ZvKdsyr0VeIRZY1WevniZ+smFNwhpmzpmjZjBkMBIGA1UdEwEB/wQIMAYBAf8CAQAwHwYDVR0jBBgwFoAUrJEQUzO9vmhB/6cMqeX66uXli
            qEwHQYDVR0OBBYEFD7jXRwEGanJtDH4hHTW4eFXcuObMA4GA1UdDwEB/wQEAwIBBjAKBggqhkjOPQQDAwNpADBmAjEAu76IjXONBQLPvP1m
            bQlXUDW81ocsP4QwSSYp7dH5FOh5mRya6LWu+NOoVDP3tg0GAjEAqzjt0MyB7QCkUsO6RPmTY2VT/swpfy60359evlpKyraZXEuCDfkEOG9
            4B7tYlDm3Z3JlY2VpcHRZDl0wgAYJKoZIhvcNAQcCoIAwgAIBATEPMA0GCWCGSAFlAwQCAQUAMIAGCSqGSIb3DQEHAaCAJIAEggPoMYIEGD
            AsAgECAgEBBCQ5Q1lISk5HNjQ0LmF0LmFzaXRwbHVzLm9lZ3YtZGVtby1hcHAwggL1AgEDAgEBBIIC6zCCAucwggJtoAMCAQICBgF3tFVXU
            zAKBggqhkjOPQQDAjBPMSMwIQYDVQQDDBpBcHBsZSBBcHAgQXR0ZXN0YXRpb24gQ0EgMTETMBEGA1UECgwKQXBwbGUgSW5jLjETMBEGA1UE
            CAwKQ2FsaWZvcm5pYTAeFw0yMTAyMTcwODUwMjdaFw0yMTAyMjAwODUwMjdaMIGRMUkwRwYDVQQDDEA0NjAyM2VjODc3ZjAxZjYwZDI3MWU
            wNDczMjQxMzZjMThlNDBmODRiN2UzOTBmMDk0NjYwMjQ1ZmVmMGJjOTNlMRowGAYDVQQLDBFBQUEgQ2VydGlmaWNhdGlvbjETMBEGA1UECg
            wKQXBwbGUgSW5jLjETMBEGA1UECAwKQ2FsaWZvcm5pYTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABAk7F4ZDIPRx3H1fr2bn3Yqvd4GgY
            m7btrLtuajILCNagKcdGu7uwpsW/uJ3BmvyYhXQ4BOpKbTMrxovzu8GrmyjgfEwge4wDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCBPAw
            fgYJKoZIhvdjZAgFBHEwb6QDAgEKv4kwAwIBAb+JMQMCAQC/iTIDAgEBv4kzAwIBAb+JNCYEJDlDWUhKTkc2NDQuYXQuYXNpdHBsdXMub2V
            ndi1kZW1vLWFwcKUGBARza3Mgv4k2AwIBBb+JNwMCAQC/iTkDAgEAv4k6AwIBADAZBgkqhkiG92NkCAcEDDAKv4p4BgQEMTQuNDAzBgkqhk
            iG92NkCAIEJjAkoSIEIBfigX3P10gT5lQj6T0eIFa8oBCf9mN8bdvh4JqmSWlsMAoGCCqGSM49BAMCA2gAMGUCMQCqq2PxXYSg03Ng6dZha
            iOT5Tz6us/LmesoSlAQz40fCKLw9qZUcxLP2fp86q/gQd4CMEw5ybrh0tHMEGqqAVrHU+DoSlo3tVapyfth8epkZ4imSQ5SKkXKGFOrXXBH
            oFJQCDAoAgEEAgEBBCCxsaqdYsvQYJBamhcj0XSbhC7lFPgCH72kRISh3e7iszBgAgEFAgEBBFhkTm5raVlJcS8wMGJ4UXg3RVdteXU2QVB
            BMUVJNjVOUjJaNzVreEVQK1ZMSG4xYWxPd25tQTdDUWpqRmVsWWpZWUtjV2NqOWszWmJUdmc3WlF3SFZOUT09MA4CAQYCAQEEBkFUVEVTVD
            APAgEHAgEBBAdzYW5kYm94MCACAQwCAQEEGDIwMjEtMAQ0Mi0xOFQwODo1MDoyNy44MDRaMCACARUCAQEEGDIwMjEtMDUtMTlUMDg6NTA6M
            jcuODA0WgAAAAAAAKCAMIIDrTCCA1SgAwIBAgIQWTNWreVZgs9EQjes30UbUzAKBggqhkjOPQQDAjB8MTAwLgYDVQQDDCdBcHBsZSBBcHBs
            aWNhdGlvbiBJbnRlZ3JhdGlvbiBDQSA1IC0gRzExJjAkBgNVBAsMHUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MRMwEQYDVQQKDAp
            BcHBsZSBJbmMuMQswCQYDVQQGEwJVUzAeFw0yMDA1MTkxNzQ3MzFaFw0yMTA2MTgxNzQ3MzFaMFoxNjA0BgNVBAMMLUFwcGxpY2F0aW9uIE
            F0dGVzdGF0aW9uIEZyYXVkIFJlY2VpcHQgU2lnbmluZzETMBEGA1UECgwKQXBwbGUgSW5jLjELMAkGA1UEBhMCVVMwWTATBgcqhkjOPQIBB
            ggqhkjOPQMBBwNCAAR/6RU0bMOKe5g8k9HQQ1/Yq9pWcATTLFiGZVGVerR498sq+LpF9/p46sYsSeT5zcCEtQMU8QIz2pt2+kQqK7hyo4IB
            2DCCAdQwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBTZF/5LZ5A4S5L0287VV4AUC489yTBDBggrBgEFBQcBAQQ3MDUwMwYIKwYBBQUHMAG
            GJ2h0dHA6Ly9vY3NwLmFwcGxlLmNvbS9vY3NwMDMtYWFpY2E1ZzEwMTCCARwGA1UdIASCARMwggEPMIIBCwYJKoZIhvdjZAUBMIH9MIHDBg
            grBgEFBQcCAjCBtgyBs1JlbGlhbmNlIG9uIHRoaXMgY2VydGlmaWNhdGUgYnkgYW55IHBhcnR5IGFzc3VtZXMgYWNjZXB0YW5jZSBvZiB0a
            GUgdGhlbiBhcHBsaWNhYmxlIHN0YW5kYXJkIHRlcm1zIGFuZCBjb25kaXRpb25zIG9mIHVzZSwgY2VydGlmaWNhdGUgcG9saWN5IGFuZCBj
            ZXJ0aWZpY2F0aW9uIHByYWN0aWNlIHN0YXRlbWVudHMuMDUGCCsGAQUFBwIBFilodHRwOi8vd3d3LmFwcGxlLmNvbS9jZXJ0aWZpY2F0ZWF
            1dGhvcml0eTAdBgNVHQ4EFgQUaR7HD0fs443ddTdE8+nhWmwQViUwDgYDVR0PAQH/BAQDAgeAMA8GCSqGSIb3Y2QMDwQCBQAwCgYIKoZIzj
            0EAwIDRwAwRAIgJRgWXF4pnFn2hTmtXduZ9jc+9g7NCEWp/Xca1iQtLCICIF0qmypfq6NjgWWNGED3r0gL12uhlNg0IIf01pNbtRuuMIIC+
            TCCAn+gAwIBAgIQVvuD1Cv/jcM3mSO1Wq5uvTAKBggqhkjOPQQDAzBnMRswGQYDVQQDDBJBcHBsZSBSb290IENBIC0gRzMxJjAkBgNVBAsM
            HUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MRMwEQYDVQQKDApBcHBsZSBJbmMuMQswCQYDVQQGEwJVUzAeFw0xOTAzMjIxNzUzMzN
            aFw0zNDAzMjIwMDAwMDBaMHwxMDAuBgNVBAMMJ0FwcGxlIEFwcGxpY2F0aW9uIEludGVncmF0aW9uIENBIDUgLSBHMTEmMCQGA1UECwwdQX
            BwbGUgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxEzARBgNVBAoMCkFwcGxlIEluYy4xCzAJBgNVBAYTAlVTMFkwEwYHKoZIzj0CAQYIKoZIz
            j0DAQcDQgAEks5jvX2GsasoCjsc4a/7BJSAkaz2Md+myyg1b0RL4SHlV90SjY26gnyVvkn6vjPKrs0EGfEvQyX69L6zy4N+uqOB9zCB9DAP
            BgNVHRMBAf8EBTADAQH/MB8GA1UdIwQYMBaAFLuw3qFYM4iapIqZ3r6966/ayySrMEYGCCsGAQUFBwEBBDowODA2BggrBgEFBQcwAYYqaHR
            0cDovL29jc3AuYXBwbGUuY29tL29jc3AwMy1hcHBsZXJvb3RjYWczMDcGA1UdHwQwMC4wLKAqoCiGJmh0dHA6Ly9jcmwuYXBwbGUuY29tL2
            FwcGxlcm9vdGNhZzMuY3JsMB0GA1UdDgQWBBTZF/5LZ5A4S5L0287VV4AUC489yTAOBgNVHQ8BAf8EBAMCAQYwEAYKKoZIhvdjZAYCAwQCB
            QAwCgYIKoZIzj0EAwMDaAAwZQIxAI1vpp+h4OTsW05zipJ/PXhTmI/02h9YHsN1Sv44qEwqgxoaqg2mZG3huZPo0VVM7QIwZzsstOHoNwd3
            y9XsdqgaOlU7PzVqyMXmkrDhYb6ASWnkXyupbOERAqrMYdk4t3NKMIICQzCCAcmgAwIBAgIILcX8iNLFS5UwCgYIKoZIzj0EAwMwZzEbMBk
            GA1UEAwwSQXBwbGUgUm9vdCBDQSAtIEczMSYwJAYDVQQLDB1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTETMBEGA1UECgwKQXBwbG
            UgSW5jLjELMAkGA1UEBhMCVVMwHhcNMTQwNDMwMTgxOTA2WhcNMzkwNDMwMTgxOTA2WjBnMRswGQYDVQQDDBJBcHBsZSBSb290IENBIC0gR
            zMxJjAkBgNVBAsMHUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MRMwEQYDVQQKDApBcHBsZSBJbmMuMQswCQYDVQQGEwJVUzB2MBAG
            ByqGSM49AgEGBSuBBAAiA2IABJjpLz1AcqTtkyJygRMc3RCV8cWjTnHcFBbZDuWmBSp3ZHtfTjjTuxxEtX/1H7YyYl3J6YRbTzBPEVoA/Vh
            YDKX1DyxNB0cTddqXl5dvMVztK517IDvYuVTZXpmkOlEKMaNCMEAwHQYDVR0OBBYEFLuw3qFYM4iapIqZ3r6966/ayySrMA8GA1UdEwEB/w
            QFMAMBAf8wDgYDVR0PAQH/BAQDAgEGMAoGCCqGSM49BAMDA2gAMGUCMQCD6cHEFl4aXTQY2e3v9GwOAEZLuN+yRhHFD/3meoyhpmvOwgPUn
            PWTxnS4at+qIxUCMG1mihDK1A3UT82NQz60imOlM27jbdoXt2QfyFMm+YhidDkLF1vLUagM6BgD56KyKAAAMYH9MIH6AgEBMIGQMHwxMDAu
            BgNVBAMMJ0FwcGxlIEFwcGxpY2F0aW9uIEludGVncmF0aW9uIENBIDUgLSBHMTEmMCQGA1UECwwdQXBwbGUgQ2VydGlmaWNhdGlvbiBBdXR
            ob3JpdHkxEzARBgNVBAoMCkFwcGxlIEluYy4xCzAJBgNVBAYTAlVTAhBZM1at5VmCz0RCN6zfRRtTMA0GCWCGSAFlAwQCAQUAMAoGCCqGSM
            49BAMCBEcwRQIhALisa5Ay4zkZmoqdVd5k/qydlU9ud4W9JYxLScmeITOiAiACDvXXDFr1CvycxshX2nRqGsIy308BGP9IB7t+TFDA/wAAA
            AAAAGhhdXRoRGF0YVikjiSVS1qsC3yiRa+Gw3NrIPZ0W9pBspx+KbwXluNyqeVAAAAAAGFwcGF0dGVzdGRldmVsb3AAIEYCPsh38B9g0nHg
            RzJBNsGOQPhLfjkPCUZgJF/vC8k+pQECAyYgASFYIAk7F4ZDIPRx3H1fr2bn3Yqvd4GgYm7btrLtuajILCNaIlgggKcdGu7uwpsW/uJ3Bmv
            yYhXQ4BOpKbTMrxovzu8Grmw=
        """.trimIndent().decodeBase64ToArray()!!

        val expectedPublicKey =
            "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAECTsXhkMg9HHcfV+vZufdiq93gaBibtu2su25qMgsI1qApx0a7u7Cmxb+4ncGa/JiFdDgE6kptMyvGi/O7waubA==".decodeBase64ToArray()

        service.extractVerifiedPublicKey(
            listOf(attestationStatement),
            Date.from(Instant.parse("2021-02-17T10:00:00Z"))
        ) shouldBe expectedPublicKey
    }

}