[versions]
qrcode = "4.5.0"
pgsql = "42.7.7"
mockito = "6.2.1"
vck = "7.0.0"
nimbus = "10.7"

spring-boot = "4.1.0"
spring-cloud = "2025.1.2"
spring-admin-starter-client = "4.1.1"

webjars-locator = "0.47"
webjars-bootstrap = "5.3.1"
webjars-jquery = "3.7.1"
webjars-datatables = "1.13.5"

kotlin = "2.3.0"

[libraries]
spring-boot-admin-starter-client = { module = "de.codecentric:spring-boot-admin-starter-client", version.ref = "spring-admin-starter-client" }
nimbus-jose-jwt = { module = "com.nimbusds:nimbus-jose-jwt", version.ref = "nimbus" }
webjars-locator = { module = "org.webjars:webjars-locator", version.ref = "webjars-locator" }
webjars-bootstrap = { module = "org.webjars:bootstrap", version.ref = "webjars-bootstrap" }
webjars-jquery = { module = "org.webjars:jquery", version.ref = "webjars-jquery" }
webjars-datatables = { module = "org.webjars:datatables", version.ref = "webjars-datatables" }
qrcode-kotlin = { module = "io.github.g0dkar:qrcode-kotlin", version.ref = "qrcode" }
wallet-vck = { module = "at.asitplus.wallet:vck", version.ref = "vck" }
wallet-vck-openid-ktor = { module = "at.asitplus.wallet:vck-openid-ktor", version.ref = "vck" }

postgresql = { module = "org.postgresql:postgresql", version.ref = "pgsql" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito" }
spring-cloud-config-dependencies = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "spring-cloud" }
spring-cloud-starter-config = { module = "org.springframework.cloud:spring-cloud-starter-config" }

[bundles]
wallet = [
  "wallet-vck",
  "wallet-vck-openid-ktor"
]
