package at.asitplus.wallet.backend.config

import io.swagger.v3.oas.models.Components
import io.swagger.v3.oas.models.OpenAPI
import io.swagger.v3.oas.models.info.Info
import io.swagger.v3.oas.models.media.Content
import io.swagger.v3.oas.models.media.MediaType
import io.swagger.v3.oas.models.responses.ApiResponse
import io.swagger.v3.oas.models.security.SecurityScheme
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.info.BuildProperties
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration


/**
 * Sets useful information for the OpenAPI specs generated by this service.
 */
@Configuration
class OpenApiConfiguration {

    @Autowired
    lateinit var buildProperties: BuildProperties

    @Bean
    fun customOpenAPI(): OpenAPI {
        return OpenAPI()
            .components(
                Components().addSecuritySchemes(
                    "oidcPupil",
                    SecurityScheme()
                        .type(SecurityScheme.Type.OPENIDCONNECT)
                        .description("OIDC authentication with ID Austria")
                )
                    .addResponses(
                        "errorResponse", ApiResponse().description("Internal server error").content(
                            Content().addMediaType(
                                "application/json", MediaType().example( // From Spring's DefaultErrorAttributes
                                    "{\n" +
                                            "    \"error\": \"Internal Server Error\",\n" +
                                            "    \"exception\": \"java.lang.IllegalArgumentException\",\n" +
                                            "    \"message\": \"foo\",\n" +
                                            "    \"path\": \"/credentials/status/1\",\n" +
                                            "    \"status\": 500,\n" +
                                            "    \"timestamp\": \"2022-05-18T08:24:17.239+00:00\"\n" +
                                            "}"
                                )
                            )
                        )
                    )
            )
            .info(Info().title("Wallet Backend").description("Wallet Backend Service").version(buildProperties.version))
    }
}