package at.asitplus.wallet.backend.config

import at.asitplus.wallet.backend.auth.WebSecurityConstants
import at.asitplus.wallet.backend.auth.WebSecurityConstants.X_API_KEY
import at.asitplus.wallet.backend.auth.WebSecurityConstants.X_AUTH_EXT_NONCE
import at.asitplus.wallet.backend.auth.WebSecurityConstants.X_AUTH_TOKEN
import io.swagger.v3.oas.models.Components
import io.swagger.v3.oas.models.OpenAPI
import io.swagger.v3.oas.models.info.Info
import io.swagger.v3.oas.models.media.Content
import io.swagger.v3.oas.models.media.MediaType
import io.swagger.v3.oas.models.responses.ApiResponse
import io.swagger.v3.oas.models.security.SecurityScheme
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.info.BuildProperties
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.http.HttpHeaders


/**
 * Sets useful information for the OpenAPI specs generated by this service.
 */
@Configuration
class OpenApiConfiguration {

    @Autowired
    lateinit var buildProperties: BuildProperties

    @Bean
    fun customOpenAPI(): OpenAPI {
        return OpenAPI()
            .components(
                Components().addSecuritySchemes(
                    "extNonce",
                    SecurityScheme()
                        .type(SecurityScheme.Type.APIKEY)
                        .name(X_AUTH_EXT_NONCE)
                        .`in`(SecurityScheme.In.HEADER)
                        .description("Nonce to be scanned from QR Code created by ECO, to be transmitted in the header `$X_AUTH_EXT_NONCE`.")
                ).addSecuritySchemes(
                    "xAuthToken",
                    SecurityScheme()
                        .type(SecurityScheme.Type.APIKEY)
                        .name(X_AUTH_TOKEN)
                        .`in`(SecurityScheme.In.HEADER)
                        .description("Session identifier from the previous response, contained in the header `$X_AUTH_TOKEN`.")
                ).addSecuritySchemes(
                    "apiKey",
                    SecurityScheme()
                        .type(SecurityScheme.Type.APIKEY)
                        .name(X_API_KEY)
                        .`in`(SecurityScheme.In.HEADER)
                        .description("API Key to be used for calls to the revocation controller, contained in header `$X_API_KEY`.")
                ).addSecuritySchemes(
                    "deviceBinding",
                    SecurityScheme()
                        .type(SecurityScheme.Type.HTTP)
                        .scheme("bearer")
                        .bearerFormat("JWT")
                        .description("Response to challenge sent in header `WWW—Authenticate`, shall contain JWT signed with device binding key.")
                )
                    .addResponses(
                        "errorResponse", ApiResponse().description("Internal server error").content(
                            Content().addMediaType(
                                "application/json", MediaType().example( // From Spring's DefaultErrorAttributes
                                    "{\n" +
                                            "    \"error\": \"Internal Server Error\",\n" +
                                            "    \"exception\": \"java.lang.IllegalArgumentException\",\n" +
                                            "    \"message\": \"foo\",\n" +
                                            "    \"path\": \"/credentials/status/1\",\n" +
                                            "    \"status\": 500,\n" +
                                            "    \"timestamp\": \"2022-05-18T08:24:17.239+00:00\"\n" +
                                            "}"
                                )
                            )
                        )
                    )
            )
            .info(Info().title("PupilId API").description("PupilId Backend Service").version(buildProperties.version))
    }
}