logging:
  level:
    at.asitplus.wallet.backend.auth.ApiKeyAuthnFilter: OFF
    at.asitplus.wallet.backend.auth.DeviceBindingAuthnFilter: OFF
    at.asitplus.wallet.backend.auth.ExtNonceAuthnFilter: OFF
spring:
  profiles:
    default: pupilid
  config:
    import:
  cloud:
    config:
      enabled: false
backend:
  authn:
    deviceBinding:
      attestation:
        noop: true
  credentials:
    pictures:
      pathLibJni: "http/libwebp/libwebp_jni.so"