spring:
  application:
    name: ${SPRING_APPLICATION_NAME:wallet-issuing-backend}
  threads:
    virtual:
      enabled: true
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:}
  cloud:
    config:
      enabled: ${SPRING_CLOUD_CONFIG_ENABLED:false}
      uri: ${SPRING_CLOUD_CONFIG_URI:}
